# Generated by Django 5.2.7 on 2026-01-31 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=100)),
                ('prod_desc', models.CharField(max_length=50)),
                ('prod_volume', models.CharField(max_length=30)),
                ('prod_uom', models.CharField(max_length=30)),
                ('prod_supid', models.CharField(max_length=10)),
                ('prod_life', models.CharField(max_length=30)),
                ('prod_weight', models.CharField(max_length=30)),
                ('prod_condition', models.CharField(max_length=100)),
                ('prod_branch', models.CharField(max_length=10)),
                ('prod_pic', models.ImageField(blank=True, null=True, upload_to='product_images/')),
            ],
        ),
        migrations.CreateModel(
            name='supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sup_name', models.CharField(max_length=100)),
                ('sup_email', models.CharField(max_length=50)),
                ('sup_phone', models.CharField(max_length=30)),
                ('sup_country', models.CharField(max_length=30)),
                ('sup_city', models.CharField(max_length=20)),
                ('sup_address', models.CharField(max_length=200)),
                ('sup_desc', models.CharField(max_length=300)),
                ('sup_pic', models.ImageField(blank=True, null=True, upload_to='supplier_images/')),
                ('sup_blc', models.FloatField(default=0, max_length=50)),
            ],
        ),
    ]
