# Generated by Django 5.2.7 on 2026-02-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_product_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='asn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sup_id', models.CharField(max_length=10)),
                ('prod_id', models.CharField(max_length=50)),
                ('volume', models.CharField(max_length=30)),
                ('uom', models.CharField(max_length=30)),
                ('qty', models.CharField(max_length=10)),
                ('branch_id', models.CharField(max_length=5)),
                ('sno', models.CharField(max_length=30)),
                ('batch', models.CharField(max_length=50)),
                ('asn_no', models.CharField(max_length=10)),
            ],
        ),
    ]
