# Generated by Django 5.2.7 on 2026-02-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_asn'),
    ]

    operations = [
        migrations.CreateModel(
            name='stockin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_asnno', models.CharField(max_length=30)),
                ('sup_id', models.CharField(max_length=10)),
                ('prod_id', models.CharField(max_length=50)),
                ('qty', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=20)),
                ('dt', models.CharField(max_length=20)),
                ('branch_id', models.CharField(max_length=5)),
                ('truck_no', models.CharField(max_length=15)),
                ('remarks', models.CharField(max_length=50)),
                ('transporter', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=5)),
                ('final', models.CharField(max_length=5)),
                ('serial_no', models.CharField(max_length=50)),
                ('gatepass_id', models.CharField(max_length=10)),
                ('asn_qty', models.CharField(max_length=10)),
                ('asn_balance', models.CharField(max_length=10)),
                ('pack', models.CharField(max_length=10)),
                ('pack_rec', models.CharField(max_length=10)),
                ('Pack_blc', models.CharField(max_length=10)),
                ('loose', models.CharField(max_length=10)),
                ('loose_rec', models.CharField(max_length=10)),
                ('loose_blc', models.CharField(max_length=10)),
                ('batch', models.CharField(max_length=50)),
                ('expiry', models.CharField(max_length=20)),
                ('cond', models.CharField(max_length=20)),
                ('cond_qty', models.CharField(max_length=5)),
                ('return_status', models.CharField(max_length=20)),
                ('return_qty', models.CharField(max_length=10)),
                ('return_dat', models.CharField(max_length=10)),
                ('return_gid', models.CharField(max_length=10)),
                ('return_balance', models.CharField(max_length=10)),
                ('rec_userid', models.CharField(max_length=5)),
                ('rec_dat', models.CharField(max_length=10)),
                ('rec_tim', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=10)),
                ('access', models.CharField(max_length=10)),
                ('mfg', models.CharField(max_length=20)),
                ('checked', models.CharField(max_length=5)),
                ('verified', models.CharField(max_length=5)),
                ('approved', models.CharField(max_length=5)),
                ('weightp', models.CharField(max_length=10)),
                ('weight_rec', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='asn',
            name='asn_no',
            field=models.CharField(max_length=30),
        ),
    ]
