# Generated by Django 5.2.7 on 2026-02-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_asn_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='asn',
            name='remarks',
            field=models.CharField(default='', max_length=100),
        ),
    ]
