# Generated by Django 5.2.7 on 2026-02-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_asn_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='asn',
            name='trns',
            field=models.CharField(default='0', max_length=30),
        ),
        migrations.AddField(
            model_name='asn',
            name='veh',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
