# Generated by Django 5.2.7 on 2026-02-18 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_asn_trns_asn_veh'),
    ]

    operations = [
        migrations.CreateModel(
            name='gatepass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gp_asnno', models.CharField(default=0, max_length=30)),
                ('driver', models.CharField(default=0, max_length=10)),
                ('cnic', models.CharField(default=0, max_length=30)),
                ('mobile', models.CharField(default=0, max_length=20)),
                ('typ', models.CharField(max_length=20)),
                ('indt', models.CharField(max_length=50)),
                ('outdt', models.CharField(max_length=50)),
                ('branch_id', models.CharField(max_length=5)),
                ('remarks', models.CharField(max_length=50)),
                ('transporter', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=5)),
                ('final', models.CharField(max_length=5)),
                ('seal', models.CharField(max_length=50)),
            ],
        ),
    ]
