# Generated by Django 5.2.7 on 2026-02-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_gatepass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockin',
            name='asn_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockin',
            name='asn_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockin',
            name='cond_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockin',
            name='qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
