# Generated by Django 5.2.7 on 2026-02-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_stockin_asn_balance_alter_stockin_asn_qty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='stockin_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_id', models.CharField(max_length=20)),
                ('qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mfg', models.CharField(max_length=20)),
                ('expiry', models.CharField(max_length=20)),
                ('weight_rec', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
