# Generated by Django 5.2.7 on 2026-02-23 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_stockin_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockin_detail',
            name='weight_rec',
        ),
        migrations.AlterField(
            model_name='stockin_detail',
            name='expiry',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='stockin_detail',
            name='mfg',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='stockin_detail',
            name='qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stockin_detail',
            name='rec_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.stockin'),
        ),
    ]
