# Generated by Django 5.2.7 on 2026-02-24 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_remove_stockin_detail_weight_rec_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockin',
            name='rec_dat',
            field=models.DateField(max_length=10),
        ),
        migrations.AlterField(
            model_name='stockin',
            name='rec_tim',
            field=models.TimeField(max_length=10),
        ),
    ]
