# Generated by Django 5.2.7 on 2026-02-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_alter_stockin_rec_dat_alter_stockin_rec_tim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockin',
            name='rec_tim',
            field=models.TimeField(),
        ),
    ]
