# Generated by Django 5.2.7 on 2026-02-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_alter_stockin_rec_tim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockin',
            name='location',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
