# Generated by Django 5.2.7 on 2026-02-25 14:07

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_alter_stockin_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_id', models.IntegerField()),
                ('batch_id', models.CharField(blank=True, max_length=50, null=True)),
                ('blc', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('block_stock', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('expire_stock', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('location_name', models.CharField(max_length=100)),
                ('dat', models.DateField(auto_now_add=True)),
                ('mfg_dat', models.DateField(blank=True, null=True)),
                ('expiry_dat', models.DateField(blank=True, null=True)),
                ('stockin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='app1.stockin')),
            ],
        ),
    ]
