# Generated by Django 5.2.7 on 2026-02-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='dn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sup_id', models.CharField(max_length=10)),
                ('prod_id', models.CharField(max_length=50)),
                ('volume', models.CharField(max_length=30)),
                ('uom', models.CharField(max_length=30)),
                ('qty', models.CharField(max_length=10)),
                ('branch_id', models.CharField(max_length=5)),
                ('sno', models.CharField(max_length=30)),
                ('batch', models.CharField(max_length=50)),
                ('dn_no', models.CharField(max_length=30)),
                ('veh', models.CharField(default=0, max_length=20)),
                ('dealer', models.CharField(default=0, max_length=30)),
                ('remarks', models.CharField(default=0, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='stockout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockout_orderno', models.CharField(default=0, max_length=30)),
                ('sup_id', models.CharField(default=0, max_length=10)),
                ('prod_id', models.CharField(default=0, max_length=50)),
                ('qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dat', models.DateField(auto_now_add=True)),
                ('dt', models.CharField(default=0, max_length=20)),
                ('branch_id', models.CharField(default=0, max_length=5)),
                ('truck_no', models.CharField(default=0, max_length=15)),
                ('remarks', models.CharField(default=0, max_length=50)),
                ('dealer', models.CharField(default=0, max_length=50)),
                ('user_id', models.CharField(default=0, max_length=5)),
                ('final', models.CharField(default=0, max_length=5)),
                ('serial_no', models.CharField(default=0, max_length=50)),
                ('gatepass_id', models.CharField(default=0, max_length=10)),
                ('dn_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dnn_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('volume', models.CharField(default=0, max_length=30)),
                ('uom', models.CharField(default=0, max_length=30)),
                ('pack', models.CharField(default=0, max_length=10)),
                ('pack_deliver', models.CharField(default=0, max_length=10)),
                ('Pack_blc', models.CharField(default=0, max_length=10)),
                ('loose', models.CharField(default=0, max_length=10)),
                ('loose_rec', models.CharField(default=0, max_length=10)),
                ('loose_blc', models.CharField(default=0, max_length=10)),
                ('batch', models.CharField(default=0, max_length=50)),
                ('expiry', models.CharField(default=0, max_length=20)),
                ('return_status', models.CharField(default=0, max_length=20)),
                ('return_qty', models.CharField(default=0, max_length=10)),
                ('return_dat', models.CharField(default=0, max_length=10)),
                ('return_gid', models.CharField(default=0, max_length=10)),
                ('return_balance', models.CharField(default=0, max_length=10)),
                ('rec_userid', models.CharField(default=0, max_length=5)),
                ('weightp', models.CharField(default=0, max_length=10)),
                ('weight_rec', models.CharField(default=0, max_length=10)),
            ],
        ),
    ]
