# Generated by Django 5.2.7 on 2026-02-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_dn_stockout'),
    ]

    operations = [
        migrations.CreateModel(
            name='dn_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dn_no', models.CharField(max_length=30)),
                ('prod_id', models.CharField(max_length=50)),
                ('item', models.CharField(max_length=100)),
                ('batch', models.CharField(max_length=30)),
                ('qty', models.CharField(max_length=10)),
                ('veh', models.CharField(max_length=30)),
                ('dealer', models.CharField(max_length=50)),
            ],
        ),
    ]
