# Generated by Django 5.2.7 on 2026-03-04 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_dn_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_id', models.IntegerField()),
                ('batch_id', models.IntegerField()),
                ('picked_qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pick_date', models.DateField(auto_now_add=True)),
                ('pick_time', models.TimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.location')),
                ('stockout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.stockout')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.user')),
            ],
        ),
    ]
