# Generated by Django 5.2.7 on 2026-03-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_pickinghistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickinghistory',
            name='picked_confirm_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pickinghistory',
            name='picked_confirm_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pickinghistory',
            name='picked_confirm_user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
