# Generated by Django 5.2.7 on 2026-04-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_outgatepass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='prod_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
