# Generated by Django 5.2.7 on 2026-04-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_alter_location_prod_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='productbarcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=100)),
                ('product_barcode', models.CharField(max_length=100)),
            ],
        ),
    ]
