# Generated by Django 5.2.7 on 2026-04-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_productbarcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='sup_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
