# Generated by Django 5.2.7 on 2026-04-28 12:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_location_sup_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='uom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='volume',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
