# Generated by Django 5.2.7 on 2026-04-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_location_uom_location_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='branch',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
