# Generated by Django 5.2.7 on 2026-05-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_asn_form_ctn'),
    ]

    operations = [
        migrations.AddField(
            model_name='asn',
            name='ctn',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
